version: 2
jobs:
  js-test:
    docker:
      - image: circleci/node:10.13-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: |
            sudo npm install -g npm@latest
      - restore_cache:
          key: cf-dd-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            sudo npm install -g yarn --force
            yarn
      - save_cache:
          key: cf-dd-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache"
      - run:
          name: lint
          command: |
            yarn run lint
      - run:
          name: mocha tests
          command: |
            yarn run test
  python-test:
    docker:
      - image: circleci/python:3.7.0-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: cf-v3-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install python dependencies
          command: |
            sudo pip install pipenv
            pipenv sync -d
      - save_cache:
          key: cf-dd-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
            - "~/.cache"
      - run:
          name: run flake8
          command: |
            pipenv run flake8 . --exclude=".venv/"
      - run:
          name: run isort
          command: |
            pipenv run isort --check-only --diff --recursive --virtual-env ./.venv . --skip-glob=".venv"
      - run:
          name: run tests
          command: |
            pipenv run pytest
workflows:
  version: 2
  build-and-test:
    jobs:
      - js-test
      - python-test
